name = "Poison"
license = "GPL-3.0 License"
licenselink = "https://github.com/TheGroundZero/poison/blob/main/LICENSE.md"
description = "A pragmatic Hugo theme for bloggers.  Based on the classic \"Hyde\" design by mdo."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/TheGroundZero/poison"

# If you have a running demo of the theme.
demosite = "https://sequr.be"

tags = ["blog", "personal", "dark", "dark-mode", "light", "minimal"]
features = ["blog", "katex", "table-of-contents", "tabs", "dark-mode", "series"]

[author]
    name = "TheGroundZero"
    homepage = "https://sequr.be"

# If Porting existing theme
[original]
    author =  "poison"
    homepage = "https://poison.lukeorth.com"
    repo = "https://github.com/lukeorth/poison"
